services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: recetas_db
    volumes:
      - postgres_data:/var/lib/postgresql/data